apiVersion: apps/v1
kind: Deployment
metadata:
  name: vietsign-backend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vietsign-backend
  template:
    metadata:
      labels:
        app: vietsign-backend
    spec:
      containers:
        - name: backend
          image: jin312/vietsign-be:v1.1.31 # Updated to use potential image name
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: vietsign-backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vietsign-secrets
                  key: jwt-secret
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootUser
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: rootPassword
---
apiVersion: v1
kind: Service
metadata:
  name: vietsign-backend-service
spec:
  type: NodePort
  selector:
    app: vietsign-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
